export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const LOADING_TRUE = 'LOADING_TRUE';
export const LOADING_FALSE = 'LOADING_FALSE';
export const PUSH_PRODUCTS = 'PUSH_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS'
